### ISSUE TITLE
combination with plotly

### ISSUE THREAD

**Issue by methodds** [wbuchanan/StataJSON#16]
Hi,

many thanks for just another cool package I found created by you :)

Would it be possible to use this to feed data into the [plotly-API](https://plot.ly/javascript/)? This could be a nice way to visualize data prepared with Stata in the web.

**Comment by wbuchanan** [comment]
Just looked through the link you sent a few minutes ago.  I'm not sure it'd be directly aligned with the scope of jsonio to directly build in an interface with the Plotly JavaScript library only because it would make things less modular.  That said, it probably wouldn't be terribly difficult to throw together something that could handle some of the boilerplate to take the exported JSON and push it through their library.  In the longer term, one of my bigger interests was to build a pipeline between Stata and a Java-based application for data visualization called Dex.  It has a lot of the same features that Plotly exposes, but also would have the benefit of a bit more of an interactive GUI for developing the visualizations.  

I'm just starting a new gig so it'll take me quite some time to get any of that stuff into something resembling an alpha type release, but I'm always more than happy/willing to collaborate with folks on new things.

**Comment by wbuchanan** [comment]
@methodds after looking into this a bit more, it would require a significant amount of error for people to use a paid service (assuming others are using the service).  If I get the time I might consider doing something involving AngularJS, but don't anticipate that happening anytime in the near future.
