### ISSUE TITLE
json seprated by "\n"

### ISSUE THREAD

**Issue by py-mgmt** [wbuchanan/StataJSON#37]
My "json" file looks like below (each row is separated by \n). I can use Python pandas to read 2 rows from the file. However, jsonio only read the first row.
  {
    "villagecode":"709000300016300",
    "year":1993,
	"month":3,
	"satellite":"F10", 
	"count":18,
	"vis_mean":"46.3361", 
	"vis_sd":"17.3630", 
	"vis_min":"15.3176", 
	"vis_median":"57.5855", 
	"vis_max":"59.6481"
  }
{
  "villagecode":"709000300016300", 
	"year":1993,
	"month":4,
	"satellite":"F10", 
	"count":14,
	"vis_mean":"49.2507", 
	"vis_sd":"17.2372", 
	"vis_min":"15.9540", 
	"vis_median":"58.8517", 
	"vis_max":"60.7931"
	}

**Comment by wbuchanan** [comment]
@py-mgmt 
The issue is that your JSON is not strictly valid according to the RFC.  The objects should be separated by a comma.  If you have Stata 16 available I would recommend installing the `jsonlines` library and either outputting properly formed JSON, or using that library to parse the data you are working with.
